# Generated by Django 6.0.5 on 2026-05-25 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('fact', 'Fact'), ('preference', 'Preference'), ('emotion', 'Emotion'), ('skill', 'Skill'), ('event', 'Event')], max_length=50)),
                ('content', models.TextField()),
                ('importance', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_messages', models.ManyToManyField(blank=True, related_name='derived_memories', to='avatar.shorttermmemory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_memories', to='avatar.user')),
            ],
        ),
    ]
